apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
  namespace: web
spec: 
  dnsNames:
    - ec2-54-171-198-244.eu-west-1.compute.amazonaws.com
  secretName: app-tls
  issuerRef:
    name: selfsigned-cluster-issuer 
    kind: ClusterIssuer 
