apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec: 
  dnsNames:
    - k8snlb-b83f782db155b193.elb.eu-west-1.amazonaws.com
  secretName: argocd-secret
  issuerRef:
    name: selfsigned-issuer
