apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec: 
  dnsNames:
    - ec2-54-171-198-244.eu-west-1.compute.amazonaws.com
  secretName: argocd-cert-tls
  issuerRef:
    name: selfsigned-issuer
 
