apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec: 
  dnsNames:
    - argocd.fitaws.dk
  secretName: argocd-secret
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer 
